Repository commercetools/commercetools-docs-kit, pull requests merged in 2019-11, with the labels that each got.

#22 chore: setup percy
  .circleci/config.yml
  .percy.yml
  package.json
  packages/gatsby-theme-docs/src/design-system.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  websites/docs-smoke-test/package.json
  yarn.lock
Labels: 👨‍⚕️ Type: Tests, 🛠 Type: Tooling

#16 docs(contributing): document dev tools
  CONTRIBUTING.md
Labels: ✍️ Type: Documentation

#24 chore: setup cypress
  .circleci/config.yml
  cypress.json
  cypress/.eslintrc.yaml
  cypress/fixtures/example.json
  cypress/integration/docs-smoke-test/basic-content.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/urls.js
  package.json
  packages/gatsby-theme-docs/src/components/content-pagination.js
  test-websites/docs-smoke-test/src/content/smoke-tests/empty-page.mdx
  websites/docs-smoke-test/src/content/smoke-tests/empty-page.mdx
  yarn.lock
Labels: 👨‍⚕️ Type: Tests, 🛠 Type: Tooling

#28 Release setup
  .circleci/config.yml
  package.json
  packages/gatsby-theme-docs/.npmignore
  packages/gatsby-theme-docs/LICENSE
  packages/gatsby-theme-docs/package.json
  scripts/release_canary.sh
Labels: 🛠 Type: Tooling

#14 feat(theme): lint gatsby graphql queries
  package.json
  packages/gatsby-theme-docs/.eslintrc.js
  packages/gatsby-theme-docs/.eslintrc.yaml
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/package.json
  yarn.lock
Labels: 🛠 Type: Tooling

#36 refactor(e2e): remove unnecessary snapshots
  cypress/integration/docs-smoke-test/basic-content.js
  cypress/integration/docs-smoke-test/navigation.js
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
Labels: ⛑ Type: Refactoring, 👨‍⚕️ Type: Tests

#44 Some UI fixes according to our latest review
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/design-system.js
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/src/content/images/svg-image.mdx
Labels: 🐛 Type: Bug

#45 refactor(docs-smoke-test): remove unnecessary api pages
  websites/docs-smoke-test/src/content/api-endpoints/complexity-smoketest-post.mdx
  websites/docs-smoke-test/src/content/api-endpoints/endpoints-for-resource.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-delete-by-id.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-get-by-id.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-get-by-key.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-get.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-post-by-id.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-post.mdx
  websites/docs-smoke-test/src/content/api-endpoints/simple-resource-search.mdx
  websites/docs-smoke-test/src/content/api-types/annotations-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/any-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/array-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/boolean-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/constant-like-type.mdx
  websites/docs-smoke-test/src/content/api-types/date-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/enum-properties-type.mdx
  websites/docs-smoke-test/src/content/api-types/enum-test.mdx
  websites/docs-smoke-test/src/content/api-types/examples-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/float-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/integer-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/number-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/object-test-type-draft.mdx
  websites/docs-smoke-test/src/content/api-types/object-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/optional-property-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/out-of-order-properties-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/single-example-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/single-full-example-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/string-test-type.mdx
  websites/docs-smoke-test/src/content/api-types/union-like-type.mdx
  websites/docs-smoke-test/src/content/index.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: ⛑ Type: Refactoring

#46 feat(theme): render beta flag also on chapter title
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: 🚀 Type: New Feature

#50 refactor(code-block): no line numbers, wrap line, bash prompt
  .percy.yml
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/utils/code-block-directives.js
  packages/gatsby-theme-docs/src/utils/code-block-highlight-code.js
  packages/gatsby-theme-docs/src/utils/code-block-parse-options.js
  websites/docs-smoke-test/src/content/code-samples/code-block.mdx
  websites/docs-smoke-test/src/content/code-samples/code-with-line-highlight.mdx
Labels: ⛑ Type: Refactoring

#32 feat: mark page navigation links as active when scrolling
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/hooks/use-active-section.js
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.js
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.spec.js
  packages/gatsby-theme-docs/src/utils/safe-html-element.js
  yarn.lock
Labels: 🚀 Type: New Feature

#53 feat: subtitle
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/subtitle.js
  packages/gatsby-theme-docs/src/templates/page-content.js
Labels: 🚀 Type: New Feature

#57 refactor(theme): remove graphql linter
  package.json
  packages/gatsby-theme-docs/.eslintrc.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/generated/schema.json
  packages/gatsby-theme-docs/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#56 fix(theme): use built-in image caption
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/src/content/images/image-with-caption.mdx
  websites/docs-smoke-test/src/content/images/image.mdx
  websites/docs-smoke-test/src/content/images/inline-image.mdx
  websites/docs-smoke-test/src/content/images/svg-image.mdx
  websites/docs-smoke-test/src/content/images/tall-image.mdx
  websites/docs-smoke-test/src/content/images/transparent-image.mdx
Labels: 🐛 Type: Bug

#29 refactor(theme): to support different scenarios in Link component
  cypress/integration/docs-smoke-test/basic-content.js
  cypress/integration/docs-smoke-test/links.js
  cypress/support/env.js
  cypress/support/urls.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/content-pagination.js
  packages/gatsby-theme-docs/src/components/external-link.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/link.js
  packages/gatsby-theme-docs/src/components/link.spec.js
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/components/seo.js
  packages/gatsby-theme-docs/src/hooks/use-site-data.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/plugins/remark-rewrite-relative-links.js
  packages/gatsby-theme-docs/src/utils/get-env.js
  websites/docs-smoke-test/src/content/smoke-tests/links.mdx
  yarn.lock
Labels: ⛑ Type: Refactoring

#61 fix(theme): prefer overflow: auto
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.spec.js
Labels: 🐛 Type: Bug

#63 feat(theme): setup cookie consent script
  packages/gatsby-theme-docs/gatsby-ssr.js
Labels: 🚀 Type: New Feature

#60 feat(theme): setup GA and make it configurable
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  websites/docs-smoke-test/gatsby-config.js
  yarn.lock
Labels: 🚀 Type: New Feature

#62 feat(theme): setup Sentry and ErrorBoundary
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/error-boundary.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/layouts/content.js
  websites/docs-smoke-test/gatsby-config.js
  yarn.lock
Labels: 🚀 Type: New Feature

#71 fix: remove page slug trailing slash
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: 🐛 Type: Bug

#72 chore: use vale local bin for vscode
  .gitignore
  .vscode/settings.json
Labels: 🔮 Type: Chore

#75 feat(theme): expose theme provider for extending site metadata
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/index.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/theme-provider.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/overrides/README.md
  packages/gatsby-theme-docs/src/overrides/use-additional-site-data.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/gatsby-config.js
Labels: 🚀 Type: New Feature

#83 chore: use new setting syntax for vscode vale extension
  .vscode/settings.json
Labels: 🛠 Type: Tooling

#58 feat: broken link checker as a standalone package
  .gitignore
  .percy.yml
  cypress/integration/docs-smoke-test/links.js
  package.json
  packages/broken-link-checker/LICENSE
  packages/broken-link-checker/README.md
  packages/broken-link-checker/broken-link-checker.js
  packages/broken-link-checker/package.json
  websites/docs-smoke-test/src/content/smoke-tests/links.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
  websites/site-template/.eslintrc.yml
  websites/site-template/gatsby-config.js
  websites/site-template/package.json
  websites/site-template/src/content/index.mdx
  websites/site-template/src/data/navigation.yaml
  yarn.lock
Labels: 🚀 Type: New Feature

#82 Legacy raml parser plugin
  packages/gatsby-transformer-raml-legacy/README.md
  packages/gatsby-transformer-raml-legacy/__tests__/from-api/create-endpoint-nodes/post-process-endpoints.js
  packages/gatsby-transformer-raml-legacy/__tests__/from-api/create-types-nodes/post-process-types.js
  packages/gatsby-transformer-raml-legacy/docs/developing.md
  packages/gatsby-transformer-raml-legacy/gatsby-node.js
  packages/gatsby-transformer-raml-legacy/index.js
  packages/gatsby-transformer-raml-legacy/package.json
  packages/gatsby-transformer-raml-legacy/src/create-api-node.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-endpoints-nodes/create-endpoints-nodes.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-endpoints-nodes/index.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-endpoints-nodes/post-process-endpoints.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-nodes.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-types-nodes/create-types-nodes.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-types-nodes/index.js
  packages/gatsby-transformer-raml-legacy/src/from-api/create-types-nodes/post-process-types.js
  packages/gatsby-transformer-raml-legacy/src/helpers.js
  packages/gatsby-transformer-raml-legacy/src/includeGraph.js
  packages/gatsby-transformer-raml-legacy/src/schema/define-raml-generics.js
  packages/gatsby-transformer-raml-legacy/src/schema/define-raml-resource.js
  packages/gatsby-transformer-raml-legacy/src/schema/define-raml-type.js
  packages/gatsby-transformer-raml-legacy/src/schema/define-schema.js
  packages/gatsby-transformer-raml-legacy/src/schema/index.js
  packages/gatsby-transformer-raml-legacy/src/tracking-fs-resolver.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#86 refactor(code-block): to support title infostring
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/utils/code-block-parse-options.js
  websites/docs-smoke-test/src/content/views/code-blocks.mdx
  yarn.lock
Labels: 💅 Type: Enhancement

#96 fix(theme): use correct square icon
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/src/icons/logo.png
  packages/gatsby-theme-docs/src/icons/logo.svg
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Labels: 🐛 Type: Bug

#95 feat: run vale as a linter (using jest runners)
  .circleci/config.yml
  jest-runner-executor.config.js
  jest.test.config.js
  jest.text.config.js
  package.json
  packages/broken-link-checker/README.md
  websites/docs-smoke-test/src/content/components/content-notifications.mdx
  websites/docs-smoke-test/src/content/index.mdx
  yarn.lock
Labels: 🛠 Type: Tooling

#98 refactor(theme): use left-aligned layout
  packages/gatsby-theme-docs/src/layouts/content.js
Labels: ⛑ Type: Refactoring

#100 refactor(theme): to add favicon for light/dark theme based on media query
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-ssr.js
  packages/gatsby-theme-docs/src/icons/logo.png
  packages/gatsby-theme-docs/static/favicon-dark.png
  packages/gatsby-theme-docs/static/favicon-light.png
Labels: ⛑ Type: Refactoring

#101 fix(theme): viewport breakpoints, more fluid responsiveness
  cypress/integration/docs-smoke-test/viewports.js
  cypress/support/commands.js
  packages/gatsby-theme-docs/src/components/content-pagination.js
  packages/gatsby-theme-docs/src/design-system.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#102 fix(theme): header margins, page navigation icon
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/design-system.js
  packages/gatsby-theme-docs/src/icons/stacked-lines-indented-icon.svg
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
Labels: ⛑ Type: Refactoring

#92 feat(theme): allow to configure robots noindex
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/components/seo.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/gatsby-config.js
  websites/site-template/gatsby-config.js
Labels: 🚀 Type: New Feature

#103 fix(theme): use 32x32 size for favicons
  packages/gatsby-theme-docs/gatsby-ssr.js
  packages/gatsby-theme-docs/static/favicon-dark-32x32.png
  packages/gatsby-theme-docs/static/favicon-light-32x32.png
Labels: 🐛 Type: Bug

#90 docs(theme): document main theme features and how to use them
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/src/overrides/README.md
Labels: ✍️ Type: Documentation

#97 refactor(theme): use centered layout
  now.json
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/beta-flag.js
  packages/gatsby-theme-docs/src/components/code-block.js
  packages/gatsby-theme-docs/src/components/content-notifications.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/markdown.js
  packages/gatsby-theme-docs/src/components/theme-provider.js
  packages/gatsby-theme-docs/src/design-system.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/globals.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-centered.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/static/assets/.gitkeep
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/src/content/beta.mdx
  websites/docs-smoke-test/src/content/components/code-blocks.mdx
  websites/site-template/gatsby-config.js
  yarn.lock
Labels: 🏕 Type: Technical Exploration, 👨‍🎨 Status: UI/UX Review

#107 fix(theme): scroll for centered layout
  packages/gatsby-theme-docs/src/layouts/internals/layout-centered.js
Labels: 🐛 Type: Bug

#106 feat: plugin for introspection of mdx component placement across the site
  packages/gatsby-transformer-mdx-introspection/README.md
  packages/gatsby-transformer-mdx-introspection/__tests__/generate-component-node-object.js
  packages/gatsby-transformer-mdx-introspection/gatsby-node.js
  packages/gatsby-transformer-mdx-introspection/index.js
  packages/gatsby-transformer-mdx-introspection/package.json
  packages/gatsby-transformer-mdx-introspection/src/generate-component-node-object.js
  yarn.lock
Labels: 🚀 Type: New Feature

#110 fix(theme): some issues with responsive layout
  packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-centered.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
Labels: 🐛 Type: Bug

#111 refactor(theme): allow to slightly configure header/footer
  packages/gatsby-theme-docs/index.js
  packages/gatsby-theme-docs/src/layouts/internals/footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Labels: 💅 Type: Enhancement

#112 chore: use node v12
  .circleci/config.yml
  .nvmrc
Labels: 🔮 Type: Chore
