Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-12, with the labels that each got.

#756 feat: implement user research banner
  .changeset/calm-bulldogs-repair.md
  .changeset/six-trains-switch.md
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/top-menu.js
  packages/gatsby-theme-docs/src/components/user-research-banner.js
  packages/gatsby-theme-docs/src/icons/generated/CtLogo.js
  packages/gatsby-theme-docs/src/icons/generated/index.js
  packages/gatsby-theme-docs/src/icons/svg/ct-logo.svg
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
  packages/gatsby-theme-docs/src/overrides/page-header-banner-area.js
  packages/gatsby-theme-docs/src/overrides/top-menu-banner-area.js
  websites/api-docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  websites/api-docs-smoke-test/src/icons/github.svg
Labels: 💅 Type: Enhancement

#788 feat: Query parameter "Array" type and it's description fix
  .changeset/curvy-rings-cover.md
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
  packages/gatsby-transformer-raml/src/schema/define-raml-generic.js
  packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
  packages/gatsby-transformer-raml/src/schema/define-raml-type.js
  packages/gatsby-transformer-raml/src/schema/define-schema.js
  websites/api-docs-smoke-test/source-raml/test/api.raml
  websites/api-docs-smoke-test/src/api-specs/test/gen.properties
  websites/api-docs-smoke-test/src/api-specs/test/resources/ByProjectKeyResource.raml
Labels: 🐛 Type: Bug

#791 chore: update all dependency changeset
  .changeset/update-all-dependencies.md
Labels: 🔮 Type: Chore

#786 Feat: Implement filtering over child section nav
  .changeset/purple-kiwis-sit.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  packages/ui-kit/src/design-system.js
  websites/api-docs-smoke-test/src/content/layouts/type-regular-desktop.mdx
  websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: 🚀 Type: New Feature
