Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-04, with the labels that each got.

#330 fix: query parameters types that are objects now render as links
  packages/gatsby-theme-api-docs/src/components/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
  packages/gatsby-theme-api-docs/src/utils/generate-type-to-render.js
  websites/api-docs-smoke-test/source-raml/test/api.raml
  websites/api-docs-smoke-test/src/api-specs/test/gen.properties
  websites/api-docs-smoke-test/src/api-specs/test/resources/ByProjectKeyResource.raml
Labels: 🐛 Type: Bug

#334 chore: update cookie consent banner script
  packages/gatsby-theme-docs/gatsby-ssr.js
Labels: 🔮 Type: Chore

#350 fix: leftovers of release notes layout implementation
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/hooks/use-layout-state.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: 🐛 Type: Bug

#348 fix(theme): dynamically render the cookie consent scripts only on *.commercetools.com domain
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/gatsby-ssr.js
Labels: 🐛 Type: Bug

#351 fix(theme): remove check for zeit github branch
  packages/gatsby-theme-docs/gatsby-browser.js
Labels: 🐛 Type: Bug

#341 Tune writing style checker for plugin compatibility and custom apps
  packages/writing-style/README.md
  packages/writing-style/package.json
  packages/writing-style/vale-styles/commercetools/Acronyms.yml
  recommended.code-workspace
Labels: 💅 Type: Enhancement

#347 fix(theme): to use height auto for small screens
  .stylelintrc
  cypress/integration/docs-smoke-test/top-menu.js
  package.json
  packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
Labels: 🐛 Type: Bug

#352 Release notes list design implementation
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  packages/ui-kit/src/design-system.js
Labels: 🚀 Type: New Feature

#353 chore(ci): add workflow to verify PR labels are assigned
  .github/actions/verify-pr-labels/action.yml
  .github/actions/verify-pr-labels/index.js
  .github/actions/verify-pr-labels/package.json
  .github/actions/verify-pr-labels/yarn.lock
  .github/workflows/verify-pr-labels.yml
  lerna.json
  package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🛠 Type: Tooling

#355 refactor(theme): use uikit Stamp component for release note types
  package.json
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/content-pagination.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
  packages/gatsby-transformer-mdx-introspection/package.json
  packages/gatsby-transformer-raml-legacy/package.json
  packages/gatsby-transformer-raml/package.json
  packages/ramldoc-generator/package.json
  packages/ui-kit/package.json
  packages/ui-kit/src/design-system.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#365 refactor: release notes left over
  packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
Labels: ⛑ Type: Refactoring

#356 Writing Style: match the date formatting style hint to our actual styleguide rule
  packages/writing-style/vale-styles/commercetools/DateFormat.yml
  packages/writing-style/vale-styles/commercetools/FirstPerson.yml
  packages/writing-style/vale-styles/commercetools/Weasel.yml
Labels: 💅 Type: Enhancement

#331 Nav Content: Add Integrations marketplace to meta nav
  packages/gatsby-theme-docs/src/data/top-side-menu.yaml
Labels: 💅 Type: Enhancement

#364 feat: generate rss feed
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/package.json
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/package.json
  yarn.lock
Labels: 🚀 Type: New Feature

#369 refactor(theme): to customize Stamp using theme
  package.json
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#370 fix(theme): to not restrict content page nodes for specific filesystem
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-transformer-code-examples/gatsby-config.js
  packages/gatsby-transformer-code-examples/gatsby-node.js
Labels: 🐛 Type: Bug

#367 feat: release notes link to rss and product newsletter
  packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
  packages/gatsby-theme-docs/src/icons/rss.svg
Labels: 🚀 Type: New Feature

#380 fix(theme): rss link to be treated as external link
  packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
Labels: 🐛 Type: Bug

#375 Release Notes: Render excerpt in list with reduced formatting, show read more.
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-api-docs/src/components/type/enum.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/utils/markdown-to-react.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/index.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js
  websites/docs-smoke-test/src/releases/example-issue-resolved.mdx
  websites/docs-smoke-test/src/releases/excerpt-rendering-test.mdx
  yarn.lock
Labels: ⛑ Type: Refactoring, 🚀 Type: New Feature

#382 fix(theme): proptype warnings and mapping of some md elements
  packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js
  packages/ui-kit/src/components/markdown.js
  websites/docs-smoke-test/src/releases/excerpt-rendering-test.mdx
Labels: 🐛 Type: Bug

#376 feat(docs-theme): make beta flag available in any content
  packages/gatsby-theme-docs/src/components/beta-flag.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header.js
  packages/gatsby-theme-docs/src/markdown-components.js
  packages/ui-kit/src/design-system.js
  websites/docs-smoke-test/src/content/index.mdx
Labels: 🚀 Type: New Feature

#383 refactor(ci): to not use cypress github action
  .github/workflows/main.yml
  package.json
  yarn.lock
Labels: 🔮 Type: Chore

#386 fix: stop rendering deprecated properties
  packages/gatsby-transformer-raml/src/create-type-node.js
Labels: 🐛 Type: Bug

#384 fix(theme): sticky page nav and scrolling container
  .percy.yml
  cypress/integration/docs-smoke-test/viewports.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
  packages/gatsby-theme-docs/src/layouts/release-notes-list.js
Labels: 🐛 Type: Bug

#388 fix(theme-docs): Render mdx commonmark compliant
  packages/gatsby-theme-docs/gatsby-config.js
  websites/docs-smoke-test/src/content/index.mdx
Labels: 🐛 Type: Bug

#390 Support custom anchors in MD(X) using <Achor name="my-anchor" />
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/src/components/anchor.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/markdown-components.js
  websites/docs-smoke-test/src/content/views/custom-anchor.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: 🚀 Type: New Feature

#394 fix(theme): gracefully handle missing heading level in TOC
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.js
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.spec.js
Labels: 🐛 Type: Bug

#399 fix: inconsistent url and title or index nav
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/utils/process-table-of-content-fields.js
  packages/gatsby-theme-docs/src/utils/process-table-of-content-fields.spec.js
  yarn.lock
Labels: 🐛 Type: Bug

#400 feat(theme): allow to override top-menu links
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
Labels: 🚀 Type: New Feature

#398 enhancement(workspace): set the window title better find the window
  recommended.code-workspace
Labels: 💅 Type: Enhancement

#407 fix(theme): render proper 404 page as a content page
  now.json
  package.json
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/src/content/404.mdx
  packages/gatsby-theme-docs/src/layouts/not-found.js
  packages/gatsby-theme-docs/src/pages/404.js
  packages/gatsby-theme-docs/src/templates/page-not-found.js
Labels: 🐛 Type: Bug

#410 WIP writing style: adjustments
  packages/writing-style/.vale.ini
  packages/writing-style/styles/commercetools/Acronyms.yml
  packages/writing-style/styles/commercetools/DateFormat.yml
  packages/writing-style/styles/commercetools/FirstPerson.yml
  packages/writing-style/styles/commercetools/Weasel.yml
  packages/writing-style/styles/commercetools/WordList.yml
Labels: 💅 Type: Enhancement

#411 feat(theme): allow to configure website primary color
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/default-options.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
  packages/gatsby-theme-docs/src/layouts/release-notes-list.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  packages/gatsby-theme-docs/src/templates/release-notes-detail.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  packages/ui-kit/src/components/markdown.js
  packages/ui-kit/src/design-system.js
  websites/api-docs-smoke-test/gatsby-config.js
Labels: 🚀 Type: New Feature

#412 refactor(api-theme): compose themes in website instead of inheriting
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-api-docs/gatsby-config.js
  packages/gatsby-theme-api-docs/package.json
  websites/api-docs-smoke-test/gatsby-config.js
  websites/api-docs-smoke-test/package.json
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change
