Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-02, with the labels that each got.

#266 fix(theme): to use correct selector to exclude style elements
  packages/gatsby-theme-docs/gatsby-ssr.js
Labels: 🐛 Type: Bug

#273 refactor(theme): sync top menu links
  broken-link-checker.config.js
  packages/gatsby-theme-docs/src/data/top-menu.yaml
Labels: ⛑ Type: Refactoring

#271 refactor: expose gatsby-transformer-raml options
  packages/gatsby-theme-api-docs/gatsby-config.js
  packages/gatsby-transformer-raml/README.md
  packages/gatsby-transformer-raml/gatsby-node.js
  packages/gatsby-transformer-raml/src/create-api-node.js
  packages/gatsby-transformer-raml/src/create-resource-node.js
  packages/gatsby-transformer-raml/src/create-type-node.js
  websites/api-docs-smoke-test/gatsby-config.js
Labels: ⛑ Type: Refactoring

#272 refactor: enhanced graphql for resources
  packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
  packages/gatsby-transformer-raml/gatsby-node.js
  packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
Labels: ⛑ Type: Refactoring

#209 chore: try CI workflow with github actions
  .circleci/config.yml
  .github/workflows/main.yml
  scripts/release_canary.sh
Labels: 🛠 Type: Tooling

#276 fix: force canary releases to always publish all packages
  package.json
Labels: 🛠 Type: Tooling

#277 refactor: use more semantic HTML elements for the search crawler
  cypress/integration/docs-smoke-test/menu-navigation.js
  cypress/integration/docs-smoke-test/top-menu.js
  cypress/integration/docs-smoke-test/viewports.js
  packages/gatsby-theme-docs/src/components/content-pagination.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: ⛑ Type: Refactoring

#280 fix: publish canary only if lerna detects that packages changed
  scripts/release_canary.sh
Labels: 🔮 Type: Chore

#281 fix(actions): check out with depth 50 to allow proper canary versions on master branch
  .github/workflows/main.yml
  scripts/release_canary.sh
Labels: 🔮 Type: Chore

#288 refactor: rendering of code block for syntax highlighting
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/ui-kit/code-block-themes.js
  packages/ui-kit/package.json
  packages/ui-kit/src/components/code-block.js
  packages/ui-kit/src/components/globals.js
  packages/ui-kit/src/utils/code-block-directives.js
  packages/ui-kit/src/utils/code-block-highlight-code.js
  packages/ui-kit/src/utils/code-block-load-prism-language.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#175 feat(theme): restore scroll position of main navigation links, when navigating to a new page
  packages/gatsby-theme-docs/src/hooks/use-active-section.js
  packages/gatsby-theme-docs/src/hooks/use-scroll-position.js
  packages/gatsby-theme-docs/src/hooks/use-scroll-spy.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: 🚀 Type: New Feature

#293 fix(theme): css overrides for search overlay
  packages/gatsby-theme-docs/src/components/overlay.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
Labels: 🐛 Type: Bug
