Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-03, with the labels that each got.

#296 feat: add ramldoc-generator package
  packages/gatsby-theme-api-docs/package.json
  packages/ramldoc-generator/.gitignore
  packages/ramldoc-generator/LICENSE
  packages/ramldoc-generator/README.md
  packages/ramldoc-generator/bin/ramldoc-generator.js
  packages/ramldoc-generator/package.json
  packages/ramldoc-generator/scripts/download-rmf-codegen.js
  packages/ramldoc-generator/src/cli.js
  packages/ramldoc-generator/src/main.js
  websites/api-docs-smoke-test/package.json
  websites/api-docs-smoke-test/src/api-specs/test/gen.properties
  yarn.lock
Labels: 🚀 Type: New Feature

#311 fix(theme): remove duplicated source filesystem config
  packages/gatsby-theme-docs/gatsby-config.js
Labels: 🔮 Type: Chore

#304 feat: code examples provided on graphQL by a transformer plugin
  .eslintignore
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/code-example.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/hooks/use-code-examples.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  packages/gatsby-transformer-code-examples/LICENSE
  packages/gatsby-transformer-code-examples/README.md
  packages/gatsby-transformer-code-examples/gatsby-node.js
  packages/gatsby-transformer-code-examples/index.js
  packages/gatsby-transformer-code-examples/package.json
  packages/ui-kit/src/components/code-block.js
  packages/writing-style/vale-styles/commercetools/Acronyms.yml
  websites/docs-smoke-test/src/code-examples/example.cs
  websites/docs-smoke-test/src/code-examples/example.curl
  websites/docs-smoke-test/src/code-examples/example.graphql
  websites/docs-smoke-test/src/code-examples/example.java
  websites/docs-smoke-test/src/code-examples/example.js
  websites/docs-smoke-test/src/code-examples/example.json
  websites/docs-smoke-test/src/code-examples/example.php
  websites/docs-smoke-test/src/code-examples/example.sh
  websites/docs-smoke-test/src/code-examples/example.ts
  websites/docs-smoke-test/src/code-examples/example.yml
  websites/docs-smoke-test/src/content/components/code-examples.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
  yarn.lock
Labels: 🚀 Type: New Feature

#305 feat(theme): implement <MultiCodeExample> and <MultiCodeBlock> components
  packages/gatsby-theme-docs/src/components/code-example.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/multi-code-example.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  packages/ui-kit/src/components/code-block.js
  packages/ui-kit/src/components/markdown.js
  packages/ui-kit/src/components/multi-code-block.js
  packages/ui-kit/src/design-system.js
  packages/ui-kit/src/index.js
  websites/docs-smoke-test/src/code-examples/example.console
  websites/docs-smoke-test/src/content/components/code-examples.mdx
Labels: 🚀 Type: New Feature

#324 fix: appropriate async implementation for gatsby
  packages/gatsby-transformer-mdx-introspection/gatsby-node.js
Labels: 🐛 Type: Bug

#323 feat(writing-style): upgrade to vale 2.1.0, don't let vale fail when called from the VSCode plugin
  CONTRIBUTING.md
  packages/writing-style/.gitignore
  packages/writing-style/.vale.ini
  packages/writing-style/bin/commercetools-vale.js
  packages/writing-style/package.json
  packages/writing-style/scripts/download-vale.js
  packages/writing-style/scripts/download-writegood-styles.js
  packages/writing-style/vale-styles/commercetools/Acronyms.yml
  packages/writing-style/vale-styles/commercetools/DateFormat.yml
  packages/writing-style/vale-styles/commercetools/FirstPerson.yml
  packages/writing-style/vale-styles/commercetools/We.yml
  packages/writing-style/vale-styles/commercetools/Weasel.yml
  packages/writing-style/vale-styles/commercetools/WordList-CaseSensitive.yml
  packages/writing-style/vale-styles/commercetools/WordList.yml
  packages/writing-style/vale-styles/vocab.txt
  packages/writing-style/vale-styles/write-good/Cliches.yml
  packages/writing-style/vale-styles/write-good/E-Prime.yml
  packages/writing-style/vale-styles/write-good/Illusions.yml
  packages/writing-style/vale-styles/write-good/Passive.yml
  packages/writing-style/vale-styles/write-good/README.md
  packages/writing-style/vale-styles/write-good/So.yml
  packages/writing-style/vale-styles/write-good/ThereIs.yml
  packages/writing-style/vale-styles/write-good/TooWordy.yml
  packages/writing-style/vale-styles/write-good/Weasel.yml
  packages/writing-style/vale-styles/write-good/meta.json
Labels: ⛑ Type: Refactoring, 🐛 Type: Bug

#325 feat(theme): add support for specifying new languages for Prism
  .gitignore
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/package.json
  packages/ui-kit/src/components/multi-code-block.js
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/src/code-examples/example.scala
  websites/docs-smoke-test/src/content/components/code-examples.mdx
  yarn.lock
Labels: 🚀 Type: New Feature
