Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-11, with the labels that each got.

#742 fix: broken links to release notes samples
  packages/gatsby-theme-docs/README.md
Labels: 🐛 Type: Bug

#743 refactor: restructure rss feed table
  .changeset/calm-bulldogs-repair.md
  jest.text.config.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/ui-kit/src/components/rss-feed-table.js
  packages/ui-kit/src/components/rss-feeds.js
  packages/ui-kit/src/components/rss-feeds.spec.js
  packages/ui-kit/src/design-system.js
  websites/docs-smoke-test/src/content/components/rss-feeds.mdx
  yarn.lock
Labels: 💅 Type: Enhancement

#755 refactor: use fontsource instead of typeface package
  .changeset/wet-walls-brake.md
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/package.json
  yarn.lock
Labels: 🚀 Status: ship it

#763 chore: rehype-slug dependency update changeset
  .changeset/rehype-update.md
Labels: 🤖 Type: Dependencies

#771 fix: include commonmark in gatsby-plugin-mdx options
  .changeset/six-peaches-hope.md
  packages/gatsby-theme-docs/gatsby-config.js
  websites/docs-smoke-test/src/content/views/markdown.mdx
Labels: 🐛 Type: Bug
