Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-05, with the labels that each got.

#413 fix: element keys should be unique
  packages/gatsby-theme-docs/src/components/seo.js
Labels: 🐛 Type: Bug

#419 refactor(code-examples): make it a gatsby theme
  README.md
  packages/gatsby-theme-code-examples/LICENSE
  packages/gatsby-theme-code-examples/README.md
  packages/gatsby-theme-code-examples/gatsby-config.js
  packages/gatsby-theme-code-examples/gatsby-node.js
  packages/gatsby-theme-code-examples/index.js
  packages/gatsby-theme-code-examples/package.json
  packages/gatsby-theme-code-examples/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  packages/gatsby-theme-code-examples/src/code-example.js
  packages/gatsby-theme-code-examples/src/multi-code-example.js
  packages/gatsby-theme-code-examples/src/use-code-examples.js
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/hooks/use-code-examples.js
  packages/gatsby-theme-docs/src/markdown-components.js
  packages/gatsby-transformer-code-examples/README.md
  packages/gatsby-transformer-code-examples/gatsby-config.js
  packages/gatsby-transformer-code-examples/package.json
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/package.json
Labels: ⛑ Type: Refactoring

#422 feat: implement add-ons mechanism to merge markdown components from different add-on themes
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-api-docs/index.js
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-api-docs/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  packages/gatsby-theme-code-examples/README.md
  packages/gatsby-theme-code-examples/index.js
  packages/gatsby-theme-code-examples/package.json
  packages/gatsby-theme-code-examples/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/configure-theme.js
  packages/gatsby-theme-docs/gatsby-browser.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/gatsby-ssr.js
  packages/gatsby-theme-docs/index.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/markdown-components.js
  packages/gatsby-theme-docs/utils/bootstrap-theme-addons.js
  packages/gatsby-theme-docs/utils/create-emotion-cache.js
  packages/gatsby-theme-docs/utils/default-options.js
  packages/gatsby-theme-docs/utils/process-table-of-content-fields.js
  packages/gatsby-theme-docs/utils/process-table-of-content-fields.spec.js
  websites/api-docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/.gitignore
Labels: 💥 Type: Breaking Change, 🚀 Type: New Feature

#423 refactor: require node 12
  package.json
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/utils/bootstrap-theme-addons.js
Labels: 💥 Type: Breaking Change

#402 feat: add gatsby theme to work with constant values
  packages/gatsby-theme-code-examples/README.md
  packages/gatsby-theme-constants/LICENSE
  packages/gatsby-theme-constants/README.md
  packages/gatsby-theme-constants/gatsby-config.js
  packages/gatsby-theme-constants/gatsby-node.js
  packages/gatsby-theme-constants/index.js
  packages/gatsby-theme-constants/package.json
  packages/gatsby-theme-constants/src/constant.js
  packages/gatsby-theme-constants/src/use-constant.js
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-node.js
  websites/docs-smoke-test/gatsby-config.js
  websites/docs-smoke-test/package.json
  websites/docs-smoke-test/src/constants/limits.yaml
  websites/docs-smoke-test/src/content/index.mdx
  yarn.lock
Labels: 🚀 Type: New Feature

#424 feat: use linkinator, drop broken-link-checker
  CONTRIBUTING.md
  broken-link-checker.config.js
  linkinator.config.json
  package.json
  packages/broken-link-checker/LICENSE
  packages/broken-link-checker/README.md
  packages/broken-link-checker/bin/broken-link-checker.js
  packages/broken-link-checker/package.json
  packages/broken-link-checker/src/load-config.js
  packages/broken-link-checker/src/run.js
  websites/api-docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/.gitignore
  websites/index.html
  yarn.lock
Labels: 💥 Type: Breaking Change

#415 docs(cards): draft authoring spec proposal for cards
  websites/docs-smoke-test/src/content/components/cards.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: ✍️ Type: Documentation, 🏕 Type: Technical Exploration

#420 feat: release notes filters
  .changeset/rich-zoos-kneel.md
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
  packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
  packages/gatsby-theme-docs/src/hooks/use-filtered-release-notes.js
  packages/gatsby-theme-docs/src/hooks/use-release-notes-filter-params.js
  packages/gatsby-theme-docs/src/hooks/use-release-notes-topics.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  packages/gatsby-theme-docs/src/utils/scroll-to-top.js
  yarn.lock
Labels: 🚀 Type: New Feature

#440 cards: added icons tests cases, and more specification for titles
  websites/docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  websites/docs-smoke-test/src/content/components/cards.mdx
Labels: 🔮 Type: Chore

#441 refactor(theme): let gatsby group topics
  .changeset/eighty-eyes-travel.md
  packages/gatsby-theme-docs/src/hooks/use-release-notes-topics.js
Labels: 💅 Type: Enhancement

#446 feat: Cards
  .changeset/light-avocados-chew.md
  packages/gatsby-theme-docs/src/components/card.js
  packages/gatsby-theme-docs/src/components/cards.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/markdown-components.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js
  packages/ui-kit/src/design-system.js
  websites/docs-smoke-test/package.json
  websites/docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  websites/docs-smoke-test/src/content/components/cards.mdx
Labels: 🚀 Type: New Feature

#452 Announcement type in release notes
  .changeset/seven-games-visit.md
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
  websites/docs-smoke-test/src/releases/archive/announcement.mdx
  websites/docs-smoke-test/src/releases/release-note-template.mdx
Labels: 💅 Type: Enhancement

#454 feat(markdown): refactor content spacing to better render enclosed fragments
  .changeset/refactor-content-spacing.md
  packages/ui-kit/src/components/content-notifications.js
  packages/ui-kit/src/components/markdown.js
  packages/ui-kit/src/components/multi-code-block.js
  packages/ui-kit/src/components/subtitle.js
  websites/docs-smoke-test/src/content/components/content-notifications.mdx
Labels: 💅 Type: Enhancement

#456 feat(theme): use primary/secondary versions of prism themes for code blocks
  .changeset/new-kangaroos-smell.md
  cypress/integration/docs-smoke-test/pagination.js
  packages/gatsby-theme-code-examples/src/code-example.js
  packages/gatsby-theme-code-examples/src/multi-code-example.js
  packages/ui-kit/src/components/code-block.js
  packages/ui-kit/src/components/multi-code-block.js
  packages/ui-kit/src/design-system.js
  packages/ui-kit/src/prism-themes/commercetools.js
  packages/ui-kit/src/utils/code-block-parse-options.js
  websites/docs-smoke-test/src/content/components/code-blocks.mdx
  websites/docs-smoke-test/src/content/components/code-examples.mdx
  websites/docs-smoke-test/src/content/views/code-examples.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
Labels: 🚀 Type: New Feature

#461 refactor: render non string card body in typography container
  .changeset/good-dryers-worry.md
  packages/gatsby-theme-docs/src/components/card.js
  websites/docs-smoke-test/src/content/components/cards.mdx
Labels: 💅 Type: Enhancement

#462 fix: removes rss related warning of missing title when building
  .changeset/spicy-hotels-buy.md
  packages/gatsby-theme-docs/gatsby-config.js
Labels: 🐛 Type: Bug, 💅 Type: Enhancement

#463 fix: remove custom word spacing
  .changeset/quiet-impalas-fly.md
  packages/ui-kit/src/components/markdown.js
Labels: 💅 Type: Enhancement
