Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-10, with the labels that each got.

#702 [Breaking] refactor(theme): do not render any image in the release notes list
  .changeset/late-moons-invent.md
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/markdown-fragment-image.js
  packages/gatsby-theme-docs/src/hooks/use-resized-images.js
  packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js
Labels: 💥 Type: Breaking Change

#711 fix: stop duplicating release note pages as content pages
  .changeset/calm-suns-crash.md
  packages/gatsby-theme-docs/gatsby-node.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#692 endpoint design implementation
  .changeset/metal-points-heal.md
  packages/gatsby-theme-api-docs/src/components/resource/method/index.js
  packages/gatsby-theme-api-docs/src/components/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/resource/method/request-representation.js
  packages/gatsby-theme-api-docs/src/components/resource/method/responses.js
  packages/gatsby-theme-api-docs/src/components/resource/method/scopes.js
  packages/gatsby-theme-api-docs/src/components/resource/method/title.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url.js
  packages/gatsby-theme-api-docs/src/utils/constants.js
  packages/ui-kit/src/components/multi-code-block.js
Labels: 💅 Type: Enhancement

#714 refactor: New color for light themed header code block
  .changeset/mean-ways-clean.md
  packages/ui-kit/src/design-system.js
Labels: 💅 Type: Enhancement

#713 refactor: update top menu
  .changeset/nice-socks-lay.md
  linkinator.config.json
  packages/gatsby-theme-docs/src/data/top-menu.yaml
  packages/gatsby-theme-docs/src/data/top-side-menu.yaml
Labels: 💅 Type: Enhancement

#716 feat: include inherited properties from parent types
  .changeset/slimy-tables-float.md
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-api-docs/src/components/type/children-union-like.js
  packages/gatsby-theme-api-docs/src/components/type/children.js
  packages/gatsby-theme-api-docs/src/components/type/properties/properties.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/rows.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
  packages/gatsby-theme-api-docs/src/hooks/use-api-types.js
  packages/gatsby-theme-api-docs/src/utils/extract-additional-info.js
  packages/gatsby-transformer-raml/src/schema/define-raml-type.js
  packages/ramldoc-generator/package.json
  websites/api-docs-smoke-test/source-raml/test/types/unions.raml
  websites/api-docs-smoke-test/src/api-specs/test/api.raml
  websites/api-docs-smoke-test/src/api-specs/test/gen.properties
  websites/api-docs-smoke-test/src/api-specs/test/types/AnnotationsTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/AnyPropertiesType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/AnyTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ArrayTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/BooleanTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ChangeSomePropertyOnExampleResource.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ConstantLikeProperties.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/DateTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/DoSomeThingOnExampleResource.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/EnumPropertiesType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleResourceUpdate.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleResourceUpdateAction.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleTargetTypeKeyReference.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleTargetTypeReference.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleTargetTypeResourceIdentifier.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExamplesTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/FloatTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ImportFooForSecondPropertyToUpdateOnExampleResource.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/IntegerTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/KeyReference.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/NumberTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ObjectTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ObjectTestTypeDraft.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/OptionalPropertyTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/OutOfOrderPropertiesTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/Reference.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ReferencesTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/RegexPropertiesType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ResourceIdentifier.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/SetOfEnumTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/SoftLinkArray.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/SoftLinkObject.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/SoftLinkOutOfOrderProperties.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/StringTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLike.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeSubType1.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeSubType2.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeSubTypeWithEnumDescriptionProperties1.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeSubTypeWithEnumDescriptionProperties2.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeSubTypeWithEnumDescriptionProperties3.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/UnionLikeWithEnumDescriptionPropertiesInSubtype.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/WideLayoutArrayTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/WideLayoutFloatTestType.raml
  websites/api-docs-smoke-test/src/content/types/enums-constants-unions.mdx
Labels: 💅 Type: Enhancement

#729 refactor: add full width to tables in body column
  .changeset/nasty-houses-mate.md
  packages/ui-kit/src/components/markdown.js
  websites/docs-smoke-test/src/content/views/markdown.mdx
Labels: 💅 Type: Enhancement
