Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-06, with the labels that each got.

#469 Restructure test API to reflect real use case
  websites/api-docs-smoke-test/source-raml/test/annotation-types/annotations.raml
  websites/api-docs-smoke-test/source-raml/test/api.raml
  websites/api-docs-smoke-test/source-raml/test/security-schemes/oauth2.raml
  websites/api-docs-smoke-test/source-raml/test/types/annotations-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/any-properties-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/any-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/arrays.raml
  websites/api-docs-smoke-test/source-raml/test/types/constant-like-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/date-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/enums.raml
  websites/api-docs-smoke-test/source-raml/test/types/examples.raml
  websites/api-docs-smoke-test/source-raml/test/types/objects.raml
  websites/api-docs-smoke-test/source-raml/test/types/optional-property-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/out-of-order-properties-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/references.raml
  websites/api-docs-smoke-test/source-raml/test/types/regex-properties-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/scalars.raml
  websites/api-docs-smoke-test/source-raml/test/types/unions.raml
Labels: 💅 Type: Enhancement

#478 Fix spacing and word wrap in child navigation and lists
  .changeset/twenty-impalas-tease.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  packages/ui-kit/src/components/markdown.js
  websites/docs-smoke-test/src/content/views/two-level-index-nav.mdx
Labels: 🐛 Type: Bug

#474 Better API example test cases
  websites/api-docs-smoke-test/source-raml/test/api.raml
  websites/api-docs-smoke-test/source-raml/test/examples/array-test-type.json
  websites/api-docs-smoke-test/source-raml/test/examples/date-test-type.json
  websites/api-docs-smoke-test/source-raml/test/examples/do-something-on-example-resource.json
  websites/api-docs-smoke-test/source-raml/test/examples/example-resource-update.json
  websites/api-docs-smoke-test/source-raml/test/examples/object-test-type-draft.json
  websites/api-docs-smoke-test/source-raml/test/examples/object-test-type.json
  websites/api-docs-smoke-test/source-raml/test/examples/out-of-order-properties-test-type.json
  websites/api-docs-smoke-test/source-raml/test/examples/string-test-type.json
  websites/api-docs-smoke-test/source-raml/test/types/arrays.raml
  websites/api-docs-smoke-test/source-raml/test/types/date-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/examples.raml
  websites/api-docs-smoke-test/source-raml/test/types/objects.raml
  websites/api-docs-smoke-test/source-raml/test/types/out-of-order-properties-test-type.raml
  websites/api-docs-smoke-test/source-raml/test/types/scalars.raml
  websites/api-docs-smoke-test/src/api-specs/test/examples/ArrayTestType-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/DateTestType-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/DoSomeThingOnExampleResource-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/ExampleResourceUpdate-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/ObjectTestType-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/ObjectTestTypeDraft-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/OutOfOrderPropertiesTestType-default.json
  websites/api-docs-smoke-test/src/api-specs/test/examples/StringTestType-default.json
  websites/api-docs-smoke-test/src/api-specs/test/gen.properties
  websites/api-docs-smoke-test/src/api-specs/test/resources/ByProjectKeyResource.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ArrayTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/DateTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/DoSomeThingOnExampleResource.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ExampleResourceUpdate.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ObjectTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/ObjectTestTypeDraft.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/OutOfOrderPropertiesTestType.raml
  websites/api-docs-smoke-test/src/api-specs/test/types/StringTestType.raml
Labels: 💅 Type: Enhancement

#482 fix(theme): back to docs link from release notes pages
  .changeset/bright-gorillas-chew.md
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: 🐛 Type: Bug

#479 Index Nav: Use available space, allow touch and wheel scrolling when sticky
  .changeset/perfect-actors-sip.md
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
  yarn.lock
Labels: 💅 Type: Enhancement

#455 API docs: experimental more compact Endpoint UI
  .changeset/eleven-trains-happen.md
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-api-docs/src/components/endpoint.js
  packages/gatsby-theme-api-docs/src/components/required.js
  packages/gatsby-theme-api-docs/src/components/resource-method.js
  packages/gatsby-theme-api-docs/src/components/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/resource/method/request-representation.js
  packages/gatsby-theme-api-docs/src/components/resource/method/responses.js
  packages/gatsby-theme-api-docs/src/components/resource/method/scopes.js
  packages/gatsby-theme-api-docs/src/components/resource/method/title.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/index.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/scopes.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/title.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/url-scopes-responses.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url.js
  packages/gatsby-theme-api-docs/src/components/table.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
  packages/gatsby-theme-api-docs/src/design-system.js
  packages/gatsby-theme-api-docs/src/hooks/use-type-locations.js
  packages/gatsby-theme-api-docs/src/utils/constants.js
  packages/gatsby-theme-api-docs/src/utils/extract-additional-info.js
  packages/gatsby-theme-api-docs/src/utils/render-type-as-link.js
  packages/ui-kit/README.md
  packages/ui-kit/src/design-system.js
  websites/api-docs-smoke-test/source-raml/test/api.raml
  websites/api-docs-smoke-test/src/api-specs/test/api.raml
  websites/api-docs-smoke-test/src/content/endpoints/simple-resource-get-by-id.mdx
Labels: 💅 Type: Enhancement

#492 refactor: render api type examples with title
  .changeset/honest-crews-boil.md
  packages/gatsby-theme-api-docs/src/components/type/children-union-like.js
  packages/gatsby-theme-api-docs/src/components/type/children.js
  packages/gatsby-theme-api-docs/src/components/type/examples.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
Labels: 💅 Type: Enhancement

#498 feat: hubspot tracking
  .changeset/nasty-squids-complain.md
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  yarn.lock
Labels: 🚀 Type: New Feature

#493 feat: card with image
  .changeset/proud-singers-hang.md
  packages/gatsby-theme-docs/src/components/card.js
  websites/docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  websites/docs-smoke-test/src/content/components/cards.mdx
  websites/docs-smoke-test/src/icons/card-banner-mc-devs.svg
  websites/docs-smoke-test/src/icons/card-banner-mc-docs.svg
  websites/docs-smoke-test/src/icons/card-banner-oss.svg
  websites/docs-smoke-test/src/icons/card-banner-platform.svg
Labels: 💅 Type: Enhancement

#497 feat: rss feeds
  .changeset/khaki-apples-melt.md
  packages/ui-kit/package.json
  packages/ui-kit/src/components/rss-feeds.js
  packages/ui-kit/src/design-system.js
  packages/ui-kit/src/index.js
  websites/docs-smoke-test/package.json
  websites/docs-smoke-test/src/content/components/rss-feeds.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
  yarn.lock
Labels: 🚀 Type: New Feature

#508 refactor: allow cards to accept arbitrary children in non mdx files
  .changeset/violet-numbers-begin.md
  packages/gatsby-theme-docs/src/components/cards.js
Labels: 🐛 Type: Bug

#517 feat: option to center search dialog in its parent container
  .changeset/modern-rabbits-swim.md
  packages/gatsby-theme-docs/src/components/search-dialog.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Labels: 💅 Type: Enhancement

#522 rss feeds with custom title
  .changeset/late-queens-drum.md
  packages/ui-kit/src/components/rss-feeds.js
  websites/docs-smoke-test/src/content/components/rss-feeds.mdx
Labels: 💅 Type: Enhancement

#521 fix(bullet lists): define list styling inside containers like card
  .changeset/mean-paws-allow.md
  packages/ui-kit/src/components/globals.js
  packages/ui-kit/src/components/markdown.js
  websites/docs-smoke-test/src/content/components/cards.mdx
Labels: 💅 Type: Enhancement

#532 refactor: if example name is "default" do not render it
  packages/gatsby-theme-api-docs/src/components/type/examples.js
Labels: 💅 Type: Enhancement
