Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-01, with the labels that each got.

#207 refactor(theme): extract logo button component into uikit
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/ui-kit/src/components/logo-button.js
  packages/ui-kit/src/icons/logo.svg
  packages/ui-kit/src/index.js
Labels: ⛑ Type: Refactoring

#179 refactor(theme): to render search results in an overlay, aligned with the page content
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/components/algolia-search.js
  packages/gatsby-theme-docs/src/components/beta-flag.js
  packages/gatsby-theme-docs/src/components/error-boundary.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/search-bar.spec.js
  packages/gatsby-theme-docs/src/components/search-dialog.js
  packages/gatsby-theme-docs/src/components/search-dialog.spec.js
  packages/gatsby-theme-docs/src/components/search-input.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
  packages/gatsby-theme-docs/src/utils/report-error-to-sentry.js
  packages/ui-kit/src/components/code-block.js
  packages/ui-kit/src/components/content-notifications.js
  packages/ui-kit/src/components/globals.js
  packages/ui-kit/src/components/markdown.js
  packages/ui-kit/src/design-system.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#212 feat(theme): add missing spacing for large sizes
  packages/ui-kit/src/design-system.js
Labels: 🚀 Type: New Feature

#213 fix(theme): header layout for small screens
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Labels: 🐛 Type: Bug

#220 Missing raml fix
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-transformer-raml/README.md
Labels: 🐛 Type: Bug

#222 Method design implementation
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-api-docs/src/components/api/resource-method.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/responses.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/scopes.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/title.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/url-scopes-responses.js
  packages/gatsby-theme-api-docs/src/components/api/resource/resource.js
  packages/gatsby-theme-api-docs/src/components/api/table.js
  packages/gatsby-theme-api-docs/src/design-system.js
  packages/gatsby-theme-api-docs/src/hooks/use-read-resource-by-resource-path.js
Labels: 🚀 Type: New Feature

#223 feat(theme): implement top menu for global links
  .circleci/config.yml
  cypress/integration/docs-smoke-test/top-menu.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/top-menu.js
  packages/gatsby-theme-docs/src/data/top-menu.yaml
  packages/gatsby-theme-docs/src/data/top-side-menu.yaml
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  websites/docs-smoke-test/gatsby-config.js
Labels: 👨‍🎨 Status: UI/UX Review, 🙏 Status: Dev Review, 🚀 Type: New Feature

#224 Type design implementation
  packages/gatsby-theme-api-docs/src/components/api/required.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/responses.js
  packages/gatsby-theme-api-docs/src/components/api/table.js
  packages/gatsby-theme-api-docs/src/components/api/type/children-union-like.js
  packages/gatsby-theme-api-docs/src/components/api/type/children.js
  packages/gatsby-theme-api-docs/src/components/api/type/container.js
  packages/gatsby-theme-api-docs/src/components/api/type/description.js
  packages/gatsby-theme-api-docs/src/components/api/type/enum.js
  packages/gatsby-theme-api-docs/src/components/api/type/examples.js
  packages/gatsby-theme-api-docs/src/components/api/type/properties/properties.js
  packages/gatsby-theme-api-docs/src/components/api/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/components/api/type/properties/rows/name-type.js
  packages/gatsby-theme-api-docs/src/components/api/type/properties/rows/rows.js
  packages/gatsby-theme-api-docs/src/components/api/type/properties/type.js
  packages/gatsby-theme-api-docs/src/components/api/type/type.js
  packages/gatsby-theme-api-docs/src/components/elements/index.js
  packages/gatsby-theme-api-docs/src/components/elements/table.js
  packages/gatsby-theme-api-docs/src/utils/extract-additional-info.js
  packages/gatsby-theme-api-docs/src/utils/render-type-as-link.js
Labels: 🚀 Type: New Feature

#228 Resource design implementation
  packages/gatsby-theme-api-docs/src/components/api/resource/method/request-representation.js
  packages/gatsby-theme-api-docs/src/components/api/resource/resource.js
Labels: ⛑ Type: Refactoring

#225 refactor(theme): adjust spacings of some elements to improve visual grouping
  packages/ui-kit/src/components/code-block.js
  packages/ui-kit/src/components/globals.js
  packages/ui-kit/src/components/markdown.js
Labels: ⛑ Type: Refactoring

#227 refactor(theme): footer to contain global links as well
  broken-link-checker.config.js
  cypress/integration/docs-smoke-test/top-menu.js
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/components/top-menu.js
  packages/gatsby-theme-docs/src/data/footer.yaml
  packages/gatsby-theme-docs/src/data/top-menu.yaml
  packages/gatsby-theme-docs/src/data/top-side-menu.yaml
  packages/gatsby-theme-docs/src/icons/logo-horizontal.svg
  packages/gatsby-theme-docs/src/layouts/internals/footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
  packages/ui-kit/src/design-system.js
Labels: ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review

#231 refactor(theme): footer improvements
  packages/gatsby-theme-docs/src/components/global-navigation-link.js
  packages/gatsby-theme-docs/src/components/index.js
  packages/gatsby-theme-docs/src/components/top-menu.js
  packages/gatsby-theme-docs/src/layouts/internals/footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-footer.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/ui-kit/src/components/media-query.js
  packages/ui-kit/src/index.js
Labels: ⛑ Type: Refactoring

#232 fix(theme): beta style link
  packages/gatsby-theme-docs/src/components/beta-flag.js
Labels: 🐛 Type: Bug

#239 refactor: move components one level up
  packages/gatsby-theme-api-docs/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  packages/gatsby-theme-api-docs/src/components/endpoint.js
  packages/gatsby-theme-api-docs/src/components/endpoints-for-resource.js
  packages/gatsby-theme-api-docs/src/components/required.js
  packages/gatsby-theme-api-docs/src/components/resource-method.js
  packages/gatsby-theme-api-docs/src/components/resource/index.js
  packages/gatsby-theme-api-docs/src/components/resource/method/index.js
  packages/gatsby-theme-api-docs/src/components/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/resource/method/request-representation.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/index.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/responses.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/scopes.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/title.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/url-scopes-responses.js
  packages/gatsby-theme-api-docs/src/components/resource/resource.js
  packages/gatsby-theme-api-docs/src/components/table.js
  packages/gatsby-theme-api-docs/src/components/type/children-union-like.js
  packages/gatsby-theme-api-docs/src/components/type/children.js
  packages/gatsby-theme-api-docs/src/components/type/enum.js
  packages/gatsby-theme-api-docs/src/components/type/examples.js
  packages/gatsby-theme-api-docs/src/components/type/index.js
  packages/gatsby-theme-api-docs/src/components/type/properties/properties.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/rows.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
Labels: ⛑ Type: Refactoring

#240 Resource design implementation
  packages/gatsby-theme-api-docs/src/components/required.js
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/url-scopes-responses.js
  packages/gatsby-theme-api-docs/src/components/table.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
  packages/gatsby-theme-api-docs/src/design-system.js
Labels: 🧟 Type: Technical Debt

#234 chore: ignore .vscode/settings.json, add recommended.code-workspace
  .gitignore
  .vscode/settings.json
  .vscode/spellright.dict
  recommended.code-workspace
Labels: 🔮 Type: Chore

#233 docs: improve wording and document some missing things
  CONTRIBUTING.md
  README.md
  packages/gatsby-theme-docs/src/layouts/internals/footer.js
  packages/writing-style/vale-styles/commercetools/Acronyms.yml
Labels: ✍️ Type: Documentation

#243 fix(theme): disable search input when website has search index disabled
  packages/gatsby-theme-docs/src/components/search-input.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/ui-kit/src/design-system.js
Labels: 🐛 Type: Bug

#245 fix: union type failed to render since it has examples
  packages/gatsby-theme-api-docs/src/components/type/children-union-like.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
Labels: 🐛 Type: Bug

#244 fix(writing-style): make custom apps capitalized
  packages/writing-style/vale-styles/commercetools/Brand.yml
Labels: 🐛 Type: Bug

#247 fix(writing-style): mapping of custom apps casing
  CHANGELOG.md
  packages/gatsby-theme-docs/README.md
  packages/writing-style/vale-styles/commercetools/Brand.yml
  packages/writing-style/vale-styles/commercetools/Product.yml
Labels: 🐛 Type: Bug

#254 chore: do not format mdx files with prettier
  jest.prettier.config.js
  lint-staged.config.js
  package.json
  recommended.code-workspace
Labels: 🛠 Type: Tooling

#253 refactor(theme): to make the link underline style configurable via a prop
  packages/gatsby-theme-docs/src/components/beta-flag.js
  packages/gatsby-theme-docs/src/components/global-navigation-link.js
  packages/gatsby-theme-docs/src/components/link.js
  packages/ui-kit/src/components/link.js
Labels: 💅 Type: Enhancement

#250 feat: Production build should fail if a Type or Resource is missing or not found
  packages/gatsby-theme-api-docs/src/components/resource-method.js
  packages/gatsby-theme-api-docs/src/components/resource/resource.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
  packages/gatsby-theme-api-docs/src/utils/report-error.js
Labels: 🏕 Type: Technical Exploration

#261 fix(theme): use data-link-type instead of aria role attribute
  packages/gatsby-theme-docs/src/components/link.js
  packages/gatsby-theme-docs/src/components/link.spec.js
  packages/ui-kit/src/components/markdown.js
Labels: 🐛 Type: Bug

#260 fix(theme): sidebar link border color
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Labels: 🐛 Type: Bug

#257 fix: import api bugs
  packages/gatsby-theme-api-docs/src/components/resource/method/method.js
  packages/gatsby-theme-api-docs/src/components/resource/resource.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
  packages/gatsby-theme-api-docs/src/hooks/use-type-locations.js
  packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
  packages/gatsby-transformer-raml/src/utils/resource/process-methods.js
  yarn.lock
Labels: 🐛 Type: Bug

#265 fix(theme): to patch lobotomized owl selector to ignore style children
  packages/gatsby-theme-docs/gatsby-ssr.js
Labels: 🐛 Type: Bug
