Repository commercetools/commercetools-docs-kit, pull requests merged in 2020-09, with the labels that each got.

#630 fix: index menu inconsistent highlighting when content menu is used
  .changeset/warm-dolphins-laugh.md
  cypress/integration/docs-smoke-test/child-sections-nav.js
  packages/gatsby-theme-docs/src/layouts/internals/page-navigation.js
  websites/docs-smoke-test/src/content/views/nested-headings.mdx
  websites/docs-smoke-test/src/content/views/two-level-index-nav.mdx
Labels: 🐛 Type: Bug

#642 refactor: update readmes
  README.md
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-docs/README.md
  packages/gatsby-transformer-raml/README.md
  packages/ramldoc-generator/README.md
  websites/docs-smoke-test/package.json
Labels: 💅 Type: Enhancement

#647 feat: enable wide layout in docs smoke test
  websites/docs-smoke-test/gatsby-config.js
Labels: 💅 Type: Enhancement

#654 refactor: spacing in code example title bar
  .changeset/metal-ladybugs-eat.md
  packages/ui-kit/src/components/multi-code-block.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#653 refactor: align nav-buttons in wide layout into the middle
  .changeset/thirty-ears-call.md
  packages/gatsby-theme-docs/src/components/content-pagination.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#664 auto-generate src/images/releases directory
  .changeset/calm-masks-hunt.md
  packages/gatsby-theme-docs/gatsby-node.js
Labels: 💅 Type: Enhancement

#666 feat: include canonical urls
  .changeset/three-oranges-happen.md
  linkinator.config.json
  packages/gatsby-theme-docs/README.md
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/utils/default-options.js
  yarn.lock
Labels: 🚀 Type: New Feature
