Repository commercetools/commercetools-docs-kit, pull requests merged in 2021-12, with the labels that each got.

#1166 Don't render a dash when parameter has no description
  .changeset/good-dingos-search.md
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
Labels: 💅 Type: Enhancement

#1160 Update and Improve Algolia Docsearch Setup
  .changeset/silly-pugs-bake.md
  algolia-crawler.js
  packages/gatsby-theme-api-docs/src/components/description.js
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/table.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
  packages/gatsby-theme-docs/src/components/algolia-search.js
  packages/gatsby-theme-docs/src/components/cards.js
Labels: 💅 Type: Enhancement, 🐛 Type: Bug

#1177 Implement formatting for regex in query parameters
  .changeset/orange-jars-teach.md
  api-specs/test/types/regex-properties-type.raml
  packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
  packages/gatsby-theme-api-docs/src/components/type/properties/regex-properties.js
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
Labels: 🚀 Type: New Feature
