Repository commercetools/commercetools-docs-kit, pull requests merged in 2021-01, with the labels that each got.

#821 Update Vale version, fix style rule and reformat YAML
  .changeset/fuzzy-guests-wave.md
  .github/workflows/main.yml
  cypress/integration/docs-smoke-test/links.js
  lint-staged.config.js
  package.json
  packages/gatsby-theme-api-docs/README.md
  packages/gatsby-theme-docs/README.md
  packages/ramldoc-generator/README.md
  packages/writing-style/package.json
  packages/writing-style/styles/Google/AMPM.yml
  packages/writing-style/styles/Google/Acronyms.yml
  packages/writing-style/styles/Google/Colons.yml
  packages/writing-style/styles/Google/Contractions.yml
  packages/writing-style/styles/Google/DateFormat.yml
  packages/writing-style/styles/Google/Ellipses.yml
  packages/writing-style/styles/Google/EmDash.yml
  packages/writing-style/styles/Google/EnDash.yml
  packages/writing-style/styles/Google/Exclamation.yml
  packages/writing-style/styles/Google/FirstPerson.yml
  packages/writing-style/styles/Google/Gender.yml
  packages/writing-style/styles/Google/GenderBias.yml
  packages/writing-style/styles/Google/HeadingPunctuation.yml
  packages/writing-style/styles/Google/Headings.yml
  packages/writing-style/styles/Google/Latin.yml
  packages/writing-style/styles/Google/LyHyphens.yml
  packages/writing-style/styles/Google/OptionalPlurals.yml
  packages/writing-style/styles/Google/Ordinal.yml
  packages/writing-style/styles/Google/OxfordComma.yml
  packages/writing-style/styles/Google/Parens.yml
  packages/writing-style/styles/Google/Passive.yml
  packages/writing-style/styles/Google/Periods.yml
  packages/writing-style/styles/Google/Quotes.yml
  packages/writing-style/styles/Google/Ranges.yml
  packages/writing-style/styles/Google/Semicolons.yml
  packages/writing-style/styles/Google/Slang.yml
  packages/writing-style/styles/Google/Spacing.yml
  packages/writing-style/styles/Google/Spelling.yml
  packages/writing-style/styles/Google/Units.yml
  packages/writing-style/styles/Google/We.yml
  packages/writing-style/styles/Google/Will.yml
  packages/writing-style/styles/Google/WordList.yml
  packages/writing-style/styles/Google/meta.json
  packages/writing-style/styles/Google/vocab.txt
  packages/writing-style/styles/commercetools/FirstPerson.yml
  packages/writing-style/styles/commercetools/Weasel.yml
  packages/writing-style/styles/commercetools/WordList-CaseSensitive.yml
  packages/writing-style/styles/commercetools/WordList.yml
  packages/writing-style/styles/write-good/Illusions.yml
  websites/docs-smoke-test/src/code-examples/example.yml
  websites/docs-smoke-test/src/content/components/cards.mdx
  websites/docs-smoke-test/src/content/views/code-examples.mdx
  websites/docs-smoke-test/src/content/views/custom-anchor.mdx
  websites/docs-smoke-test/src/content/views/links.mdx
  websites/site-template/src/content/index.mdx
Labels: 🛠 Type: Tooling, 🤖 Type: Dependencies

#842 fix: size of grey hovering area in child section nav
  .changeset/spicy-knives-give.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
Labels: 🐛 Type: Bug

#832 feat: script for generating release note files
  .changeset/slow-ants-tie.md
  packages/gatsby-theme-docs/bin/create-release-note.js
  packages/gatsby-theme-docs/package.json
  yarn.lock
Labels: 🚀 Type: New Feature

#844 fix: javascript bundle fails on development
  .changeset/spotty-scissors-nail.md
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-code-examples/package.json
  packages/gatsby-theme-constants/package.json
  packages/gatsby-theme-docs/package.json
  websites/api-docs-smoke-test/package.json
  websites/docs-smoke-test/package.json
  websites/site-template/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#840 Updates acronyms in writing style checker
  .changeset/smart-meals-camp.md
  packages/writing-style/styles/commercetools/Acronyms.yml
Labels: 💅 Type: Enhancement
