Repository commercetools/commercetools-docs-kit, pull requests merged in 2021-03, with the labels that each got.

#885 Match package.json engine to .nvmrc for vercel ( Node v14 LTS)
  package.json
Labels: 🤖 Type: Dependencies

#869 Implement icons for microsite title
  .changeset/spicy-sheep-juggle.md
  packages/gatsby-theme-docs/src/icons/generated/index.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/overrides/site-icon.js
  packages/ui-kit/src/icons/generated/CustomApplication.js
  packages/ui-kit/src/icons/generated/CustomApplicationSmall.js
  packages/ui-kit/src/icons/generated/HttpApi.js
  packages/ui-kit/src/icons/generated/HttpApiSmall.js
  packages/ui-kit/src/icons/generated/MerchantCenter.js
  packages/ui-kit/src/icons/generated/MerchantCenterSmall.js
  packages/ui-kit/src/icons/generated/OpenSource.js
  packages/ui-kit/src/icons/generated/OpenSourceSmall.js
  packages/ui-kit/src/icons/generated/Tutorials.js
  packages/ui-kit/src/icons/generated/TutorialsSmall.js
  packages/ui-kit/src/icons/generated/index.js
  packages/ui-kit/src/icons/svg/HTTP-API-small.svg
  packages/ui-kit/src/icons/svg/HTTP-API.svg
  packages/ui-kit/src/icons/svg/custom-application-small.svg
  packages/ui-kit/src/icons/svg/custom-application.svg
  packages/ui-kit/src/icons/svg/merchant-center-small.svg
  packages/ui-kit/src/icons/svg/merchant-center.svg
  packages/ui-kit/src/icons/svg/open-source-small.svg
  packages/ui-kit/src/icons/svg/open-source.svg
  packages/ui-kit/src/icons/svg/tutorials-small.svg
  packages/ui-kit/src/icons/svg/tutorials.svg
  packages/ui-kit/src/index.js
  websites/api-docs-smoke-test/src/@commercetools-docs/gatsby-theme-docs/overrides/site-icon.js
Labels: 💅 Type: Enhancement

#886 update RMF codegen
  .changeset/eight-chefs-nail.md
  packages/rmf-codegen/package.json
Labels: 🤖 Type: Dependencies

#889 hotfix: remove icon exports from theme
  .changeset/eight-planets-lie.md
  packages/gatsby-theme-docs/src/icons/generated/index.js
Labels: 🐛 Type: Bug

#880 ISO 31 (international) number formating for constants and API
  .changeset/cuddly-dodos-peel.md
  packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
  packages/gatsby-theme-constants/src/constant.js
  packages/ui-kit/package.json
  packages/ui-kit/src/index.js
  packages/ui-kit/src/utils/iso-number-format.js
  websites/docs-smoke-test/src/constants/limits.yaml
  websites/docs-smoke-test/src/content/views/markdown.mdx
  yarn.lock
Labels: 💅 Type: Enhancement

#908 update user research banner text
  .changeset/chatty-humans-juggle.md
  packages/gatsby-theme-docs/src/components/user-research-banner.js
Labels: 💅 Type: Enhancement

#878 Move searchbox over index nav
  .changeset/blue-gorillas-agree.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  packages/gatsby-theme-docs/src/components/search-dialog.js
  packages/gatsby-theme-docs/src/components/search-input.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
  packages/ui-kit/src/components/media-query.js
  packages/ui-kit/src/design-system.js
Labels: 💅 Type: Enhancement

#911 Fix overlapping entries in child section nav
  .changeset/silly-actors-remain.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
Labels: 🐛 Type: Bug

#907 Improve release note generator
  .changeset/itchy-timers-lick.md
  packages/gatsby-theme-docs/bin/create-release-note.js
  packages/gatsby-theme-docs/package.json
  websites/api-docs-smoke-test/package.json
  websites/docs-smoke-test/docs-release-notes-config.yml
  websites/docs-smoke-test/package.json
Labels: 💅 Type: Enhancement
