Repository commercetools/commercetools-docs-kit, pull requests merged in 2022-02, with the labels that each got.

#1220 Update writing style checker
  .changeset/shy-wombats-wink.md
  packages/writing-style/styles/commercetools/Acronyms.yml
Labels: User: Docs

#1228 Implement subsection support in child-section-nav
  .changeset/ten-camels-enjoy.md
  packages/gatsby-theme-docs/src/components/child-sections-nav.js
  websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
  websites/documentation/src/content/writing/navigation.mdx
Labels: 🚀 Type: New Feature

#1231 fix: make dependent gatsby plugins actual dependencies
  .changeset/clean-ants-repair.md
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-constants/package.json
  websites/documentation/src/content/configuration/packages.mdx
  yarn.lock
Labels: 🤖 Type: Dependencies

#1238 Implement reading time estimation with auto time estimation option
  .changeset/moody-oranges-explode.md
  packages/gatsby-theme-docs/gatsby-node.js
  packages/gatsby-theme-docs/src/layouts/content.js
  packages/gatsby-theme-docs/src/layouts/internals/page-read-time-estimation.js
  packages/gatsby-theme-docs/src/templates/page-content.js
  websites/docs-smoke-test/src/content/views/beta.mdx
  websites/docs-smoke-test/src/content/views/code-blocks.mdx
  websites/docs-smoke-test/src/content/views/code-examples.mdx
  websites/docs-smoke-test/src/content/views/custom-anchor.mdx
  websites/docs-smoke-test/src/content/views/links.mdx
  websites/docs-smoke-test/src/content/views/markdown.mdx
  websites/docs-smoke-test/src/content/views/nested-headings.mdx
  websites/docs-smoke-test/src/content/views/two-level-index-nav.mdx
  websites/docs-smoke-test/src/content/views/wide.mdx
  websites/documentation/src/content/writing/pages.mdx
Labels: 🚀 Type: New Feature
