Repository commercetools/commercetools-docs-kit, pull requests merged in 2022-03, with the labels that each got.

#1249 Apply writing style improvements
  .changeset/cool-carrots-push.md
  packages/writing-style/styles/commercetools/Product.yml
Labels: 💅 Type: Enhancement

#1248 Lowercase section headings in release note filter
  .changeset/wicked-parents-mate.md
  packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
  packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
Labels: 💅 Type: Enhancement

#1253 Ability to write mermaid diagrams via code blocks (like gitHub)
  .changeset/stupid-colts-do.md
  .github/renovate.json
  lint-staged.config.js
  packages/gatsby-theme-api-docs/package.json
  packages/gatsby-theme-api-docs/src/utils/transform-urn-links-plugin.js
  packages/gatsby-theme-docs/gatsby-config.js
  packages/gatsby-theme-docs/package.json
  packages/gatsby-theme-docs/src/markdown-components.js
  packages/gatsby-theme-docs/src/plugins/remark-mdx-mermaid.js
  packages/ui-kit/package.json
  packages/ui-kit/src/components/mermaid-client-side.tsx
  packages/ui-kit/src/components/mermaid.tsx
  packages/ui-kit/src/index.ts
  packages/ui-kit/src/mermaid.d.ts
  recommended.code-workspace
  websites/docs-smoke-test/src/content/components/mermaid-diagram.mdx
  websites/docs-smoke-test/src/data/navigation.yaml
  websites/documentation/src/content/index.mdx
  websites/documentation/src/content/writing/images.mdx
  websites/documentation/src/data/navigation.yaml
  websites/documentation/src/images/dog.jpg
  yarn.lock
Labels: 🚀 Type: New Feature

#1250 Fix: set max-width for enums
  .changeset/afraid-lamps-sort.md
  api-specs/test/types/arrays.raml
  packages/gatsby-theme-api-docs/src/components/resource/method/request-representation.js
  packages/gatsby-theme-api-docs/src/components/type/enum.js
  packages/gatsby-theme-api-docs/src/components/type/type.js
  packages/ui-kit/src/design-system.ts
  websites/api-docs-smoke-test/src/content/types/enums-constants-unions.mdx
Labels: 🐛 Type: Bug
