Repository commercetools/commercetools-docs-kit, pull requests merged in 2024-06, with the labels that each got.

#1998 feat: create utils for generating release notes urls with right filters
  .changeset/cold-owls-grab.md
  packages/gatsby-theme-docs/index.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/utils/release-notes.js
  packages/gatsby-theme-docs/src/utils/release-notes.spec.js
Labels: missing-jira, 10 min review

#1987 chore: remove filters from release notes list page
  .changeset/rotten-snakes-scream.md
  packages/gatsby-theme-docs/src/components/link.js
  packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
  packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
  packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
  packages/gatsby-theme-docs/src/hooks/use-release-notes-filter-params.js
  packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
  packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
  packages/gatsby-theme-docs/src/layouts/release-notes-list.js
  packages/gatsby-theme-docs/src/utils/release-notes.js
  packages/gatsby-theme-docs/src/utils/release-notes.spec.js
Labels: missing-jira, 10 min review

#2000 fix: attempt to fix release notes links
  .changeset/tough-dots-rest.md
  packages/gatsby-theme-docs/src/components/link.js
  packages/gatsby-theme-docs/src/hooks/use-release-notes-config.js
  packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
  packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
  packages/gatsby-theme-docs/src/utils/release-notes.js
  packages/gatsby-theme-docs/src/utils/release-notes.spec.js
Labels: missing-jira

#2002 chore: fix the product and productArea value inversion
  .changeset/olive-suns-battle.md
  packages/gatsby-theme-docs/src/hooks/use-release-notes-config.js
Labels: missing-jira

#2005 chore: adapt release notes back links to the new format
  .changeset/curvy-chefs-look.md
  packages/gatsby-theme-docs/src/hooks/use-release-notes-config.js
  packages/gatsby-theme-docs/src/utils/release-notes.js
  packages/gatsby-theme-docs/src/utils/release-notes.spec.js
Labels: missing-jira

#2007 Ga release notes infobox
  .changeset/empty-camels-wait.md
  packages/gatsby-theme-docs/src/layouts/release-notes-list.js
Labels: missing-jira

#2010 fix: use correct link component to go back to release note page
  .changeset/chilled-mayflies-itch.md
  packages/gatsby-theme-docs/src/layouts/release-notes-list.js
Labels: missing-jira

#2011 [release notes] Introduce new `hideProductLabels` frontmatter
  .changeset/ninety-lamps-greet.md
  packages/gatsby-theme-docs/gatsby-node.mjs
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
  packages/gatsby-theme-docs/src/templates/release-notes-detail.js
  packages/gatsby-theme-docs/src/templates/release-notes-list.js
  websites/docs-smoke-test/src/releases/release-note-without-product-labels.mdx
  websites/documentation/src/content/writing/release-notes.mdx
Labels: missing-jira

#2015 Make confirmation dialog more configurable
  .changeset/real-singers-lie.md
  packages/ui-kit/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx
  packages/ui-kit/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/ui-kit/src/components/dialogs/internals/dialog-footer.tsx
Labels: missing-jira

#2017 Ga release notes tags
  .changeset/spotty-elephants-happen.md
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
  packages/ui-kit/src/design-system.ts
Labels: missing-jira

#2019 chore: make release notes tag responsive
  .changeset/blue-foxes-lay.md
  packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
Labels: missing-jira

#2013 fix: all release notes link with no filters
  .changeset/gold-olives-nail.md
  packages/gatsby-theme-docs/src/hooks/use-release-notes-config.js
  packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
Labels: missing-jira

#2023 feat: adjust rss component to new rss structure
  .changeset/fuzzy-rabbits-hang.md
  packages/ui-kit/src/components/rss/rss-feed-table.tsx
  packages/ui-kit/src/components/rss/rss-feeds.spec.ts
  packages/ui-kit/src/components/rss/rss-feeds.tsx
  websites/docs-smoke-test/src/content/components/rss-feeds.mdx
Labels: missing-jira

#2025 fix: adjust rss custom tag name
  .changeset/wet-wasps-repeat.md
  packages/ui-kit/src/components/rss/rss-feeds.spec.ts
  packages/ui-kit/src/components/rss/rss-feeds.tsx
Labels: missing-jira

#2028 Improve documentation of the `orderHint` release note frontmatter
  websites/documentation/src/content/writing/release-notes.mdx
Labels: ✍️ Type: Documentation

#2029 feat: support code blocks in self-learning
  .changeset/beige-cycles-teach.md
  cypress/e2e/self-learning-smoke-test/04-quiz.feature
  cypress/e2e/self-learning-smoke-test/04-quiz.ts
  packages/gatsby-theme-docs/src/modules/self-learning/components/quiz-form.tsx
  packages/ui-kit/src/components/multi-code-block.tsx
  websites/self-learning-smoke-test/gatsby-config.mjs
  websites/self-learning-smoke-test/src/content/course-with-code/overview.mdx
  websites/self-learning-smoke-test/src/content/course-with-code/quiz.mdx
Labels: missing-jira
